name: Deploy to AWS Lambda

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5
      

    - name: Terraform Init
      run: terraform init
      working-directory: terraform
      env:
        

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform
      env:
        
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}|}
    

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 216989135585.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t todo-app .

    - name: Tag Docker image
      run: |
        docker tag todo-app:latest 216989135585.dkr.ecr.us-east-1.amazonaws.com/todo-app-repo:latest

    - name: Push Docker image to ECR
      run: |
        docker push 216989135585.dkr.ecr.us-east-1.amazonaws.com/todo-app-repo:latest
