name: Build Image on DockerHub

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-todo:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-todo:latest

