name: Semantic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the correct GitVersion Action
      - name: Install GitVersion
        uses: GitTools/actions/gitversion-action@v0.9.10  # Use the correct and working version

      # Run GitVersion and set VERSION environment variable
      - name: Calculate Semantic Version
        id: version
        run: |
          VERSION=$(gitversion /output json | jq -r .FullSemVer)
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save the version to GitHub environment

      # Continue with the rest of your build
      - name: Build project
        working-directory: ./src
        run: dotnet build


      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dotnet-todo:$VERSION .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dotnet-todo:$VERSION
